name: Continuous Integration

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request_target:
    types: [labeled]

jobs:
  primary:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies') || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./
