name: Continuous Integration

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request_target:
    types: [labeled]

jobs:
  primary:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies') || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ./
        with:
          directory: spec/fixtures/test_app
          dependabot_config: spec/fixtures/dependabot.yml
