name: Continuous Integration

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          persist-credentials: false
      - uses: get-bridge/dependabot-validator@v1.0.0
        with:
          directory: spec/fixtures/test_app
          dependabot_config: spec/fixtures/test_app/.github/dependabot.yml
