name: Test

on:
  pull_request_target:
    types: [labeled]
  push:
    branches-ignore:
      - "dependabot/**"
    tags-ignore:
      - '*'
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies') || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 1
          persist-credentials: false
      - uses: ./
        with:
          directory: spec/fixtures/test_app
          dependabot_config: spec/fixtures/test_app/.github/dependabot.yml
